task/urls.py
from django.urls import path

from task.views import (PositionCreateView, PositionDeleteView,
                        PositionListView, PositionUpdateView,
                        ProjectCreateView, ProjectDeleteView,
                        ProjectDetailView, ProjectListView, ProjectUpdateView,
                        TaskCreateView, TaskDeleteView, TaskDetailView,
                        TaskListView, TaskTypeCreateView, TaskTypeDeleteView,
                        TaskTypeListView, TaskTypeUpdateView, TaskUpdateView,
                        TeamCreateView, TeamDeleteView, TeamListView,
                        TeamUpdateView, WorkerCreateView, WorkerDeleteView,
                        WorkerDetailView, WorkerListView, WorkerUpdateView,
                        index)

urlpatterns = [
    path("", index, name="index"),

    path(
        "task-types/",
        TaskTypeListView.as_view(),
        name="task-type-list"
    ),

    path(
        "task-types/create",
        TaskTypeCreateView.as_view(),
        name="task-type-create"
    ),

    path(
        "task-types/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update"
    ),

    path(
        "task-types/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete"
    ),

    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"
    ),

    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create"
    ),

    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update"
    ),

    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete"
    ),

    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail"
    ),

    path(
        "positions/",
        PositionListView.as_view(),
        name="position-list"
    ),

    path(
        "positions/create/",
        PositionCreateView.as_view(),
        name="position-create"
    ),

    path(
        "positions/<int:pk>/update/",
        PositionUpdateView.as_view(),
        name="position-update"
    ),

    path(
        "positions/<int:pk>/delete/",
        PositionDeleteView.as_view(),
        name="position-delete"
    ),

    path(
        "workers/",
        WorkerListView.as_view(),
        name="worker-list"
    ),

    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create"
    ),

    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail"
    ),

    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update"
    ),

    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete"
    ),

    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list"
    ),

    path(
        "projects/<int:pk>/",
        ProjectDetailView.as_view(),
        name="project-detail"
    ),

    path(
        "projects/create/",
        ProjectCreateView.as_view(),
        name="project-create"
    ),

    path(
        "projects/<int:pk>/update/",
        ProjectUpdateView.as_view(),
        name="project-update"
    ),

    path(
        "projects/<int:pk>/delete/",
        ProjectDeleteView.as_view(),
        name="project-delete"
    ),

    path(
        "teams/",
        TeamListView.as_view(),
        name="team-list"
    ),

    path(
        "teams/create/",
        TeamCreateView.as_view(),
        name="team-create"
    ),

    path(
        "teams/<int:pk>/update/",
        TeamUpdateView.as_view(),
        name="team-update"
    ),

    path(
        "teams/<int:pk>/delete/",
        TeamDeleteView.as_view(),
        name="team-delete"
    ),

]

app_name = "task"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("task.urls", namespace="task")),
    path("accounts/", include("django.contrib.auth.urls")),

    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from task.models import Position, Project, Task, Team, Worker


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + (
             "first_name", "last_name", "position"
        )


class WorkerUpdateForm(forms.ModelForm):
    position = forms.ModelChoiceField(queryset=Position.objects.all())

    class Meta:
        model = Worker
        fields = ["first_name", "last_name", "position"]


class TaskForm(forms.ModelForm):
    assignees = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    priority = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=Task.PRIORITY
        )

    deadline = forms.DateTimeField(
        widget=forms. DateTimeInput(attrs={"type": "datetime-local"})
    )

    class Meta:
        model = Task
        fields = "__all__"


class TaskTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by username"}
        )
    )


class TeamSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )


class ProjectForm(forms.ModelForm):
    team = forms.ModelMultipleChoiceField(
        queryset=Team.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )
    status = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=Project.STATUS_CHOICES
        )

    class Meta:
        model = Project
        fields = "__all__"


class TeamForm(forms.ModelForm):
    participants = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Team
        fields = "__all__"

task/views.py
from typing import Any, Dict

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from task.forms import (PositionSearchForm, ProjectForm, ProjectSearchForm,
                        TaskForm, TaskSearchForm, TaskTypeSearchForm, TeamForm,
                        TeamSearchForm, WorkerCreationForm, WorkerSearchForm,
                        WorkerUpdateForm)
from task.models import Position, Project, Task, TaskType, Team, Worker


@login_required
def index(request):
    projects = Project.objects.prefetch_related("team")
    num_position = Position.objects.count()
    num_worker = Worker.objects.count()
    num_task = Task.objects.count()

    context = {
        "num_position": num_position,
        "num_worker": num_worker,
        "num_task": num_task,
        "projects": projects,
    }

    return render(request, "task/index.html", context=context)


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    template_name = "task/task_type_list.html"
    context_object_name = "task_type_list"
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(TaskTypeListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskTypeSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = TaskType.objects.all()
        form = TaskTypeSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task:task-type-list")
    template_name = "task/task_type_form.html"


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("task:task-type-list")
    template_name = "task/task_type_form.html"


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("task:task-type-list")
    template_name = "task/task_type_confirm_delete.html"


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(TaskListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Task.objects.select_related("task_type")
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskForm


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task
    queryset = Task.objects.select_related("task_type")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    queryset = Task.objects.select_related("task_type")
    form_class = TaskForm


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task:task-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task:position-list")
    template_name = "task/position_confirm_delete.html"


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={
                "username": username
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("task:worker-list")


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("task:worker-list")
    template_name = "task/worker_confirm_delete.html"


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(ProjectListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = ProjectSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Project.objects.all()
        form = ProjectSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    form_class = ProjectForm
    # success_url = reverse_lazy("task:project-list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    form_class = ProjectForm
    success_url = reverse_lazy("task:project-list")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("task:project-list")


class TeamListView(LoginRequiredMixin, generic.ListView):
    model = Team
    paginate_by = 10

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super(TeamListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TeamSearchForm(
            initial={
                "name": name
            }
        )
        return context

    def get_queryset(self) -> QuerySet[Any]:
        queryset = Team.objects.all()
        form = TeamSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("task:team-list")


class TeamUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    form_class = TeamForm
    success_url = reverse_lazy("task:team-list")


class TeamDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Team
    success_url = reverse_lazy("task:team-list")

templates/task/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid py-4">
  <div class="row">
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Tasks</p>
                <h5 class="font-weight-bolder mb-0" id="jsonData" data-json="{{ data }}">
                  {{ num_task }}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fa fa-tasks" aria-hidden="true"></i>
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Positions</p>
                <h5 class="font-weight-bolder mb-0" id="jsonData" data-json="{{ data }}">
                  {{ num_position }}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fa fa-street-view" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Employees</p>
                <h5 class="font-weight-bolder mb-0" id="jsonData" data-json="{{ data }}">
                  {{ num_worker }}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fa fa-user-o" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-xl-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-8">
              <div class="numbers">
                <p class="text-sm mb-0 text-capitalize font-weight-bold">Projects</p>
                <h5 class="font-weight-bolder mb-0" id="jsonData" data-json="{{ data }}">
                  {{ projects.count }}
                </h5>
              </div>
            </div>
            <div class="col-4 text-end">
              <div class="icon icon-shape bg-gradient-primary shadow text-center border-radius-md">
                <i class="fa fa-user-o" aria-hidden="true"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <div class="row mt-4">
    <div class="col-lg-7 mb-lg-0 mb-4">
      <div class="card">
        <div class="card-body p-3">
          <div class="row">
            <div class="col-lg-6">
              <div class="d-flex flex-column h-100">
                <h5 class="font-weight-bolder">IT Company Task Manager</h5>
                <p class="mb-5" style="text-align: justify;">IT management refers to the monitoring and administration of an organization's information technology systems: hardware, software and networks. IT management focuses on how to make information systems operate efficiently. Just as important, it's about helping people work better.</p>
                
              </div>
            </div>
            <div class="col-lg-5 ms-auto text-center mt-5 mt-lg-0">
              <img class="w-100 position-relative z-index-2 pt-4" src="https://www.lbtc.co.uk/wp-content/uploads/2019/11/Benefits-of-Professional-IT-Management-Courses.jpg" alt="rocket">
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-5">
      <div class="card h-100 p-3">
        <div class="overflow-hidden position-relative border-radius-lg bg-cover h-100">
          <span class="mask bg-gradient-dark"></span>
          <div class="card-body position-relative z-index-1 d-flex flex-column h-100 p-3">
            <h5 class="text-white font-weight-bolder mb-4 pt-2">Create your first project</h5>
            <p class="text-white">This IT manager help you create that you want.</p>
            <a class="text-white text-sm font-weight-bold mb-0 icon-move-right mt-auto" href="{% url 'task:project-create' %}">
              Read More
              <i class="fas fa-arrow-right text-sm ms-1" aria-hidden="true"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% if projects %}
 <div class="table-responsive">
  <table class="table table_for_index">
    <thead>
      <tr>
        <th>Project Name
        <th>Team
        <th>Status
        
    </thead>
    <tbody>
      {% for project in projects %}
        <tr>
          <td>{{ project.name }}
          <td>{{ project.team.count }}
          <td>{{ project.status }}
        </tr>
      
      {% endfor %}

    </tbody>
  </table>
 </div>
{% endif %}
</div>
{% endblock content %}

templates/task/position_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Position</h1>

    <p style="font-size: 24px;">Are you sure you want to delete position: <strong class="text-success">{{ position }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <a href="{% url 'task:position-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/task/position_form.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
  <h1 class="title">{{ object|yesno:"Update,Create" }} Position</h1>
            <form action="" method="post" novalidate>
                {% csrf_token %}
                {{ form|crispy }}
                
                    <input class="btn btn-primary" type="submit" value="Submit">
            </form>
            <a href="{% url 'task:position-list' %}"><button class="btn btn-secondary">Cancel</button></a>

{% endblock %}

templates/task/project_confirm_delete.html
{% extends "base.html" %}

{% block content %}
    <h1 class="title">Delete Project</h1>

    <p style="font-size: 24px;">Are you sure you want to delete task: <strong class="text-success">{{ project.name }}</strong></p>
    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes, delete" class="btn btn-danger">
    </form>
    <a href="{% url 'task:project-list' %}"><button class="btn btn-secondary">Cancel</button></a>
{% endblock %}

templates/task/project_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'task:project-list' %}">
  <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="text-dark" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M12.5 15a.5.5 0 0 1-.5-.5v-13a.5.5 0 0 1 1 0v13a.5.5 0 0 1-.5.5ZM10 8a.5.5 0 0 1-.5.5H3.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L3.707 7.5H9.5a.5.5 0 0 1 .5.5Z"/>
  </svg>
</a>
  <h1>{{ project.name }}</h1>
  <br>
    <div class="card z-index-2">
        <div class="card-body p-3">
         
          <h3 class="ms-2  mb-0"> Description </h3>
          <br>
          <div class="border-radius-lg">
            <div class="row">
              <p>{{ project.description }}</p>
              
            </div>
          </div>
        </div>
      </div>
      <br>
      <h2>Status</h2>
      <p>{{ project.status }}</p>
      
      
     <br>
        <h2>Team</h2>

        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <th>Username</th>
              <th>Position</th>
            </tr>
          </thead>
          <tbody>
            {% for team in project.team.all %}
              <tr>
                  <td>{{ team.name }}</td>
                  <td>
                  <table>
                    {% for user in team.participants.all %}
                      <tr>
                        <td>{{ user.username }}</td>
                      </tr>
                      {% endfor %}
                  </table>
                  </td>
                  <td>
                    <table>
                      {% for user in team.participants.all %}
                        <tr>
                          <td>{{ user.position }}</td>
                        </tr>
                        {% endfor %}
                    </table>
                  </td>
                  
                    
              </tr>
            {% empty %}
              <p>No team!</p>
            {% endfor %}
          </tbody>
          </table>

        
        <br>
    
{% endblock %}

templates/task/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">
    Tasks
  </h1>

  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}


  {% if task_list %}

  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Completion date</th>
          <th scope="col">Priority</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
          {% for task in task_list %}
          <tr>
              <th scope="row"><a class="text-dark" href="{% url 'task:task-detail' pk=task.id %}">{{ task.name }}</a></th>
              {% if task.is_completed == False %}
                <td class="text-warning">{{ task.is_completed }}</td>
              {% else %}
                <td class="text-success">{{ task.is_completed }}</td>
              {% endif %}
              <td>{{ task.priority }}</td>
              <td><a class="text-info" href="{% url 'task:task-update' pk=task.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'task:task-delete' pk=task.id %}">Delete</a></td>
          </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    
    {% else %}
      <p>The are no task in Tasks</p>
    {% endif %}
    <a class="button" style="float: right;" href="{% url 'task:task-create' %}">Create</a>
    
{% endblock %}

templates/task/task_type_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <h1 class="title">
        Task Type
      </h1>

      {% block search_form %}
        {% include "includes/search_form.html" %}
      {% endblock %}

      {% if task_type_list %}
      <div class="table-responsive">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th>Name</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
          </thead>
          <tbody>
              {% for task_type in task_type_list %}
              <tr>
                  <td>{{ task_type.name }}</td>
                  <td><a class="text-info" href="{% url 'task:task-type-update' pk=task_type.id %}">Update</a></td>
                  <td><a style="color: rgb(252, 61, 3);" href="{% url 'task:task-type-delete' pk=task_type.id %}">Delete</a></td>
              </tr>
          {% endfor %}
          </tbody>
          </table>
      </div>
        {% else %}
        <p>The are no task type in Tasks</p>
        {% endif %}
        <a class="button" style="float: right;" href="{% url 'task:task-type-create' %}">Create</a>
{% endblock %}

templates/task/team_list.html
{% extends "base.html" %}

{% block content %}
  <h1 class="title">
    Teams
  </h1>

  {% block search_form %}
    {% include "includes/search_form.html" %}
  {% endblock %}


  {% if team_list %}


  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Update</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
          {% for team in team_list %}
          <tr>
              <th scope="row">{{ team.name }}</th>
              <td><a class="text-info" href="{% url 'task:team-update' pk=team.id %}">Update</a></td>
              <td><a class="text-danger" href="{% url 'task:team-delete' pk=team.id %}">Delete</a></td>
          </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
    
    {% else %}
      <p>The are no Team in Teams</p>
    {% endif %}
    <a class="button" style="float: right;" href="{% url 'task:team-create' %}">Create</a>
    
{% endblock %}